version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
    delete:
      enabled: true
    cache:
        blobdescriptor: inmemory
    swarm:
        encrypt: false
        privateKey: 8e5c893846223894ed783acd26de67ce7d8a614107259dce1c6d6e42da4d24f57a22536487c200c38337afaa3f514ecdd38006657f4e05725baa21e4cf606892054e00dd947d6e737c4be92306d49fa4
        inmemory: false
        host: "172.22.32.1"
        port: 1633
        batchID: bf2db1100e210f274352a8c4fc5b01ede559100b4d1020dcb6fafa947fea93b3
    maintenance:
        uploadpurging:
            enabled: false
    tag:
      concurrencylimit: 8
http:
    addr: :5000
    debug:
        addr: :5001
        prometheus:
            enabled: true
            path: /metrics
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
